### ISSUE TITLE
Main hero image 

### ISSUE THREAD

**Issue by zufrieden** [antistatique/antistatique.net#206]
- [ ] Homepage blur and light the background a bit 
![screen shot 2015-06-02 at 20 02 38](https://cloud.githubusercontent.com/assets/451236/7943075/8c7c86aa-0962-11e5-995b-c99dd2ff650a.png)
- [ ] darker here ?
![screen shot 2015-06-02 at 20 05 52](https://cloud.githubusercontent.com/assets/451236/7943106/d0bc0fa2-0962-11e5-941e-00ca6574bcc7.png)

**Comment by tonifisler** [comment]
We simply cannot make it work with the images as they are here... There always will be an issue on some browser size...

**Comment by guillaumeberry** [comment]
@zufrieden As discussed wit Sepehr, we need to color grade / rework / clean the pictures. These are 'for now' placement pictures to agree on the type of image used. After that we can start fine tuning the shots!

@tonifisler Are you suggesting a top gradient?

**Comment by tonifisler** [comment]
No we already removed the top gradient because it was really not good on some cases. But I'm sure if the images are colored in this way, it will be a lot better:

![screen shot 2015-06-02 at 22 06 35](https://cloud.githubusercontent.com/assets/1708450/7945865/add56d24-0973-11e5-916f-e8750a5c3fe2.png)

(maybe not green, but with this kind of blended color overlay)

That way we avoid a too great contrast with the pink/darkbue/white of the header text and we soften the blacks and white of the image.

**Comment by guillaumeberry** [comment]
Worth the try!

**Comment by tonifisler** [comment]
Yes but the images are great without any filter :cry:

**Comment by guillaumeberry** [comment]
Now that we've experienced @Yago 's talent with photography, we can ask him to redo a shooting for the missing picture (aka “The Heim Prophecy”).

**Comment by zufrieden** [comment]
Let's display Philippe on the 500 ;-)

On Tue, Jun 2, 2015 at 10:28 PM, Guillaume Berry <notifications@github.com>
wrote:

> Now that we've experienced @Yago <https://github.com/Yago> 's talent with
> photography, we can ask him to redo a shooting for the missing picture (aka
> “The Heim Prophecy”).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/antistatique/antistatique.net/issues/206#issuecomment-108089256>
> .
>



-- 
---
Marc Friederich
marc@antistatique.net

Antistatique <http://antistatique.net/>
rue de Sébeillon 9b
1004 Lausanne
+41 21 623 63 03
www.antistatique.net
