### ISSUE TITLE
Add multiple project for a customer

### ISSUE THREAD

**Issue by dmrrlc** [antistatique/antistatique.net#211]
If I add Athena with customer "United World Wrestling", the customer is duplicated because there is already a project associated to this customer

**Comment by tonifisler** [comment]
So yeah obviously we didn't think about this use case... What I suggest is this:

- [ ] Change the field **Client** to a new taxonomy instead of a text field. This way we can add the same client to several projets and we could one day, if needed, display a client's page with all the projects we did for them.
- [ ] Add a new **Project Short Description** field, textfield
- [ ] Change the breadcrumb on projects to display the tagline: "We **work** on beautiful **projects**, like **project name here**."

/ping @zufrieden @guillaumeberry

**Comment by zufrieden** [comment]
No ! We did think about it ! 
- We said it's not an issue as there is just a few exceptions
- You'll write "an Intranet for United World Wrestling" or "a Drupal for United World Wrestling"
So don't complexify the whole model

**Comment by tonifisler** [comment]
And what about the breadcrumb?

**Comment by zufrieden** [comment]
I'm talking about the breadcrumb

**Comment by tonifisler** [comment]
:unamused: "We work on beautiful projects with people from United World Wrestling"

**Comment by zufrieden** [comment]
mmm. I see. We'll talk about that around a coffee then. Iced ☕️
We work on beautiful projects with people from IT at United World Wrestling
We work on beautiful projects with people from Communication at United World Wrestling

**Comment by tonifisler** [comment]
Ok for the coffee :+1:  

Meh :/ for the suggestions :dancer:

**Comment by gido** [comment]
I don't think it's an issue. Can we close it or move it into 1.1 ?

**Comment by tonifisler** [comment]
Moving!

**Comment by zufrieden** [comment]
closing ;-)
